version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing third-party dependencies"
      - echo "CODEBUILD_SRC_DIR is $CODEBUILD_SRC_DIR"
      - curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
      - docker run

  build:
    commands:
      - echo "Building the application"
      - syft $CODEBUILD_SRC_DIR

  post_build:
    commands:
      - echo "Running post-build steps"
