version: 0.2

phases:
  install:
    commands:
      - echo "Installing third-party dependencies"
      - aws s3 cp s3://sec1demobucket/sec1-cli-linux $CODEBUILD_SRC_DIR
      - chmod +x $CODEBUILD_SRC_DIR/sec1-cli-linux
  pre_build:
    commands:
      - echo "Setting up application"

  build:
    commands:
      - echo "Building the application"

  post_build:
    commands:
      - echo "Running Sec1 Scan"
      - $CODEBUILD_SRC_DIR/sec1-cli-linux scan $CODEBUILD_SRC_DIR --apiKey $API_KEY
