version: 0.2

phases:
  install:
    commands:
      - uname -a
  pre_build:
    commands:
      - echo "Installing third-party dependencies"
      - echo "CODEBUILD_SRC_DIR is $CODEBUILD_SRC_DIR"
      - aws s3 cp s3://sec1demobucket/sec1-cli-linux $CODEBUILD_SRC_DIR
      - chmod +x $CODEBUILD_SRC_DIR/sec1-cli-linux

  build:
    commands:
      - echo "Building the application"
      - $CODEBUILD_SRC_DIR/sec1-cli-linux scan $CODEBUILD_SRC_DIR --apiKey $API_KEY

  post_build:
    commands:
      - echo "Running post-build steps"
