version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing third-party dependencies"
      - echo "CODEBUILD_SRC_DIR is $CODEBUILD_SRC_DIR"
      - aws s3 cp s3://sec1demobucket/sec1-cli-linux /usr/local/bin

  build:
    commands:
      - echo "Building the application"
      - ls /usr/local/bin

  post_build:
    commands:
      - echo "Running post-build steps"
