version: 0.2

phases:
  install:
    commands:
      - uname -a
  pre_build:
    commands:
      - echo "Installing third-party dependencies"
      - echo "CODEBUILD_SRC_DIR is $CODEBUILD_SRC_DIR"
      - aws s3 cp s3://sec1demobucket/sec1-cli-linux $CODEBUILD_SRC_DIR
      - chmod +x $CODEBUILD_SRC_DIR/sec1-cli-linux

  build:
    commands:
      - echo "Building the application"
      - ls -ltr $CODEBUILD_SRC_DIR
      - $CODEBUILD_SRC_DIR/sec1-cli-linux scan $CODEBUILD_SRC_DIR --apiKey secone-b7acc51cc87c6b3afa6bc4e006faa73dbb317f145d8977627f69dc9e89db708f

  post_build:
    commands:
      - echo "Running post-build steps"
