version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing third-party dependencies"
      - make --version
      - brew install syft

  build:
    commands:
      - echo "Building the application"
      - syft

  post_build:
    commands:
      - echo "Running post-build steps"
