version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing third-party dependencies"
      - echo CODEBUILD_SRC_DIR
      - curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

  build:
    commands:
      - echo "Building the application"
      - syft

  post_build:
    commands:
      - echo "Running post-build steps"
